/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fantasyorder;

/**
 *
 * @author ASUS
 */
public class panelpickchar extends javax.swing.JPanel {

    int pick = 0; //archer = 1, priest 2, warrior 3
    /**
     * Creates new form panelpickchar
     */
    public panelpickchar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        archer = new javax.swing.JButton();
        priest = new javax.swing.JButton();
        warrior = new javax.swing.JButton();
        larcher = new javax.swing.JLabel();
        lpriest = new javax.swing.JLabel();
        lwarrior = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        archer.setText("Archer");
        archer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archerActionPerformed(evt);
            }
        });
        add(archer);
        archer.setBounds(510, 490, 65, 23);

        priest.setText("Priest");
        priest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priestActionPerformed(evt);
            }
        });
        add(priest);
        priest.setBounds(796, 489, 59, 23);

        warrior.setText("Warrior");
        warrior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warriorActionPerformed(evt);
            }
        });
        add(warrior);
        warrior.setBounds(1091, 490, 69, 23);

        larcher.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\FantasyOrder\\FantasyOrder\\src\\fantasyorder\\a.png")); // NOI18N
        add(larcher);
        larcher.setBounds(521, 431, 39, 48);

        lpriest.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\FantasyOrder\\FantasyOrder\\src\\fantasyorder\\p.png")); // NOI18N
        add(lpriest);
        lpriest.setBounds(805, 424, 38, 48);

        lwarrior.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\FantasyOrder\\FantasyOrder\\src\\fantasyorder\\w.png")); // NOI18N
        add(lwarrior);
        lwarrior.setBounds(1104, 423, 38, 49);

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(1110, 280, 39, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Pick Your Character");
        add(jLabel1);
        jLabel1.setBounds(510, 280, 313, 44);

        jButton2.setText("CONFIRM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(1080, 550, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void archerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archerActionPerformed
        pick = 1;
    }//GEN-LAST:event_archerActionPerformed

    private void priestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priestActionPerformed
        pick = 2;
    }//GEN-LAST:event_priestActionPerformed

    private void warriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warriorActionPerformed
        pick = 3;
    }//GEN-LAST:event_warriorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // .setJob(pick);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ini exit button ga tau mau diapakan
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel larcher;
    private javax.swing.JLabel lpriest;
    private javax.swing.JLabel lwarrior;
    private javax.swing.JButton priest;
    private javax.swing.JButton warrior;
    // End of variables declaration//GEN-END:variables
}
